---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Пользователь должен иметь возможность зарегистрироваться.
  - Пользователь должен иметь возможность авторизоваться.
  - При оформлении заказа без авторизации пользователя должны быть запрошены контактный данные (как минимум номер телефона).
  - Если язык интерфейсв выбран русский, то вся текстовая информация должна быть представлена на русском языке (за исключением названий моделей и брендов).
  - Если язык интерфейса выбран английский, то вся текстовая информация должна быть представлена на английском языке.
  - Пользователь должен иметь возможность изменить количество товара в корзине.
  - Общая стоимость товаров в корзине должна быть рассчитана корректно.
